### ISSUE TITLE
Borg Bags - Mining Satchel and Sheet Stacker Dont collect

### ISSUE THREAD

**Issue by Trilbyspaceclone** [privateroleplaysociety/odessa-outpost#13]
[Bug]
Miner Satchels and the Sheet Stacker for at lest miner Borgs do not collect anything when clicking on the.
[Round ID] - b1T-cDCz
[Remaking of bug]
Be a miner borg and try to collect anything your ment to mainly ore and sheets and fine yourself unable to!

**Comment by rpilcrow** [comment]
Seems to be an issue somewhere in borgs themselves. The ore satchel used for borgs is the same type you can pick up and use ordinarily, and borg sheet snatchers only differ in their higher capacity, empty desc, and name.
